server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AyeshaPerera1995/spring-cloud-config-store
          search-paths:
            - '*service'



